######################## default configuration ####################
baseURL = "https://demo.gethugothemes.com/educenter/examplesite/"
title = "Escuela de Computación de alto rendimiento (HPC Camp-ECAR 2022)"
theme = "ecar-2022"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "10"
# disqus short name
disqusShortname = "educenter" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = [] # desable language from here


############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/animate/animate.css"
[[params.plugins.css]]
link = "plugins/venobox/venobox.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/venobox/venobox.min.js"
[[params.plugins.js]]
link = "plugins/filterizr/jquery.filterizr.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"


#################### default parameters ################################
[params]
logo = "images/logo.png"
logo_dc = "images/logo_dc.png"
logo_csc = "images/logo_csc.png"
logo_amd = "images/logo_amd.png"
logo_fcen = "images/logo_fcen.png"
logo_risc2 = "images/logo_risc2.png"
# Meta data
description = "This is meta description"
author = "Themefisher"
# contact info
address = "Ciudad Universitaria - UBA - Pabellón Cero+Infinito, Acceso Pabellón 1, Buenos Aires"
#mobile = ""
email = "hpclatam.org"
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io
# Google Analitycs
google_analitycs_id = "" # your id
# top header
top_header = true

# Preloader
[params.preloader]
enable = true
preloader = "images/preloader.gif" # use jpg, png, svg or gif format.

# Subscription
[params.subscription]
enable = true
# mailchimp subsciption
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074" # replace this url with yours
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074" # replace this code with yours

# google map
[params.map]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
map_latitude = "-34.54369140758286"
map_longitude = "-58.44024406931197"
map_marker = "images/marker.png" # marker size 37*55 px

# cookies
[params.cookies]
enable = true
expire_days = 2

############################# social site ########################
[[params.social]]
title = "facebook"
icon = "ti-facebook" # themify icon : https://themify.me/themify-icons
link = "#"

[[params.social]]
title = "twitter"
icon = "ti-twitter-alt" # themify icon : https://themify.me/themify-icons
link = "#"

[[params.social]]
title = "instagram"
icon = "ti-instagram" # themify icon : https://themify.me/themify-icons
link = "#"

[[params.social]]
title = "github"
icon = "ti-github" # themify icon : https://themify.me/themify-icons
link = "#"

[[params.social]]
title = "linkedin"
icon = "ti-linkedin" # themify icon : https://themify.me/themify-icons
link = "#"

################################### English language #####################################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
home = "Home"
# copyright
copyright = "Copyright &copy; 2022 a hugo theme by [mmazz](https://github.com/mmazz/ecar2022), modification of the theme educenter by [Themefisher](https://themefisher.com/hugo-themes/)"



################### English navigation ####################

# main menu
[[Languages.en.menu.main]]
name = "About"
url = "about/"
weight = 1


[[Languages.en.menu.main]]
name = "Tracks"
url = "course/"
weight = 2

[[Languages.en.menu.main]]
name = "Courses"
url = "class/"
weight = 3

[[Languages.en.menu.main]]
name = "Staff"
url = "teacher/"
weight = 4


[[Languages.en.menu.main]]
name = "Contacto"
url = "contact/"
weight = 5





# footer menu

[[Languages.en.menu.footer]]
name = "teacher"
url = "teacher/"



